logging:
  level:
    evgen:
      koshmaryk: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catalog?useSSL=false
    username: root
    password: admin
    #to always initialize the DataSource
    initialization-mode: always
  jpa:
    hibernate:
      #update the schema if necessary
      ddl-auto: update
    show-sql: true